---
apiVersion: v1
kind: Namespace
metadata:
  name: value-injector
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: valueinjectors.pincette.net
spec:
  group: pincette.net
  names:
    kind: ValueInjector
    plural: valueinjectors
    singular: valueinjector
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                from:
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - kind
                  type: object
                to:
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - kind
                    - name
                  type: object
                pipeline:
                  items:
                    type: object
                  type: array
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - from
                - to
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: value-injector-controller
  labels:
    app.kubernetes.io/component: value-injector-controller
    app.kubernetes.io/name: value-injector-controller
rules:
  - apiGroups:
      - pincette.net
    resources:
      - valueinjectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pincette.net
    resources:
      - valueinjectors/status
    verbs:
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: value-injector-controller
  namespace: value-injector
  labels:
    app.kubernetes.io/component: value-injector-controller
    app.kubernetes.io/name: value-injector-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: value-injector-controller
  labels:
    app.kubernetes.io/component: value-injector-controller
    app.kubernetes.io/name: value-injector-controller
subjects:
  - kind: ServiceAccount
    name: value-injector-controller
    namespace: value-injector
roleRef:
  name: value-injector-controller
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: value-injector-controller
  namespace: value-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.kubernetes.io/name: value-injector-controller
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: value-injector-controller
    spec:
      containers:
        - name: value-injector-controller
          image: wdonne/pincette-value-injector:latest
          resources: { }
      nodeSelector:
        kubernetes.io/arch: arm64
      serviceAccountName: value-injector-controller
